version: "3"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: root
    ports:
      - 5432:5432
    volumes:
      - postgres_devx:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_devx:/data

volumes:
  postgres_devx:
  redis_devx:
